2017-02-28 14:29:00,193 ERROR: Exception on / [GET] [in D:\projects\microblog\flask\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "D:\projects\microblog\flask\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\projects\microblog\flask\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\projects\microblog\flask\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\projects\microblog\flask\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\projects\microblog\flask\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\projects\microblog\flask\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\projects\microblog\flask\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\microblog\app\views.py", line 31, in index
    posts=posts)
  File "D:\projects\microblog\flask\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "D:\projects\microblog\flask\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\microblog\app\templates\post.html", line 15, in templates
    <div><a href="{{ url_for('delete', id=post.id) }}">{{ _('Delete') }}</a> </div>
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\projects\microblog\app\templates\index.html", line 2, in top-level templates code
    {% extends "base.html" %}
  File "D:\projects\microblog\app\templates\base.html", line 61, in top-level templates code
    {% block content %}
  File "D:\projects\microblog\app\templates\index.html", line 30, in block "content"
    {% include 'post.html' %}
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\microblog\app\templates\post.html", line 15, in templates
    <div><a href="{{ url_for('delete', id=post.id) }}">{{ _('Delete') }}</a> </div>
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 212, in parse_if
    'name:endif'))
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "D:\projects\microblog\flask\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of templates. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
